export default {
  ZINDEX_SETTING: 'ZINDEX_SETTING', // 指数配置
  FAVORITE_QUOTATION_MAP: 'FAVORITE_QUOTATION_MAP', // 关注板块map
  STOCK_SETTING: 'STOCK_SETTING', // 股票配置
  COIN_SETTING: 'COIN_SETTING', // 货币配置
  SYSTEM_SETTING: 'SYSTEM_SETTING', // 系统设置
  WALLET_SETTING: 'WALLET_SETTING', // 钱包配置
  EYE_STATUS: 'EYE_STATUS', // 钱包展示状态
  CURRENT_WALLET_CODE: 'CURRENT_WALLET_CODE', // 当前选中钱包code
  FUND_SORT_MODE: 'FUND_SORT_MODE', // 基金排序模式
  FUND_VIEW_MODE: 'FUND_VIEW_MODE', // 基金视图模式
  ZINDEX_SORT_MODE: 'ZINDEX_SORT_MODE', // 指数排序模式
  ZINDEX_VIEW_MODE: 'ZINDEX_VIEW_MODE', // 指数视图模式
  QUOTATION_SORT_MODE: 'QUOTATION_SORT_MODE', // 行情排序模式
  QUOTATION_VIEW_MODE: 'QUOTATION_VIEW_MODE', // 行情视图模式
  STOCK_SORT_MODE: 'STOCK_SORT_MODE', // 股票排序模式
  STOCK_VIEW_MODE: 'STOCK_VIEW_MODE', // 股票视图模式
  COIN_SORT_MODE: 'COIN_SORT_MODE', // 货币排序模式
  COIN_VIEW_MODE: 'COIN_VIEW_MODE', // 货币视图模式
  ADJUSTMENT_NOTIFICATION_DATE: 'ADJUSTMENT_NOTIFICATION_DATE', // 上一次提醒用户调仓的时间
  REMOTE_FUND_MAP: 'REMOTE_FUND_MAP', // 远程基金库code -> map
  FUND_RATING_MAP: 'FUND_RATING_MAP', // 基金评级code -> map
  REMOTE_COIN_MAP: 'REMOTE_COIN_MAP', // 远程货币code -> map
  WEB_SETTING: 'WEB_SETTING', // 网站配置
};
