export default {
  '--background-color': '--background-color',
  '--primary-color': '--primary-color',
  '--increase-color': '--increase-color',
  '--cancel-color': '--cancel-color',
  '--cancel-text-color': '--cancel-text-color',
  '--reduce-color': '--reduce-color',
  '--main-text-color': '--main-text-color',
  '--secondary-main-text-color': '--secondary-main-text-color',
  '--reverse-text-color': '--reverse-text-color',
  '--border-color': '--border-color',
  '--alipay-color': '--alipay-color',
  '--wechat-color': '--wechat-color',
  '--svg-icon-color': '--svg-icon-color',
  '--blur-color': '--blur-color',
  '--base-font-size': '--base-font-color',
  '--base-padding': '--base-padding',
  '--warn-color': '--warn-color',
  '--inner-text-color': '--inner-text-color',
  '--increase-bg-color': '--increase-bg-color',
  '--reduce-bg-color': '--reduce-bg-color',
};
