# 仅对 Issue 生效
only: issues
# Number of days of inactivity before an issue becomes stale
daysUntilStale: 15
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 3
# Issues with these labels will never be considered stale
exemptLabels:
  - good first issue
  - enhancement
  - bug
  - dependencies
# Label to use when marking an issue as stale
staleLabel: wontfix
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: |
  感谢您的反馈🙏，为了更好的追踪问题和建议，此issue即将关闭，可能由以下原因引起：
  1. 未按照正确的issue模版提交
  2. 已经存在同类型issue，请自行搜索查看
  3. 开发者也无法解决该问题
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
