export default {
  FUND_API_TYPE: 'FUND_API_TYPE', // 数据源请求类型 2.7.0已废除
  WALLET_INDEX: 'WALLET_INDEX', // 钱包icon索引 2.8.0已废除
  FUND_SETTING: 'FUND_SETTING', // 基金配置 2.8.0已废除

  ZINDEX_SETTING: 'ZINDEX_SETTING', // 指数配置
  SYSTEM_SETTING: 'SYSTEM_SETTING', // 系统设置
  WALLET_SETTING: 'WALLET_SETTING', // 钱包配置
  EYE_STATUS: 'EYE_STATUS', // 钱包展示状态
  FUND_SORT_MODE: 'FUND_SORT_MODE', // 基金排序模式
  ZINDEX_SORT_MODE: 'ZINDEX_SORT_MODE', // 指数排序模式
  QUOTATION_SORT_MODE: 'QUOTATION_SORT_MODE', // 行情排序模式
  CURRENT_WALLET_CODE: 'CURRENT_WALLET_CODE', // 当前选中钱包code
  ADJUSTMENT_NOTIFICATION_DATE: 'ADJUSTMENT_NOTIFICATION_DATE', // 上一次提醒用户调仓的时间
};
