export default {
  FUND_SETTING: 'FUND_SETTING',
  ZINDEX_SETTING: 'ZINDEX_SETTING',
  SYSTEM_SETTING: 'SYSTEM_SETTING',
  WALLET_SETTING: 'WALLET_SETTING',
  EYE_STATUS: 'EYE_STATUS',
  FUND_API_TYPE: 'FUND_API_TYPE',
  FUND_SORT_MODE: 'FUND_SORT_MODE',
  ZINDEX_SORT_MODE: 'ZINDEX_SORT_MODE',
  QUOTATION_SORT_MODE: 'ZINDEX_SORT_MODE',
  WALLET_INDEX: 'WALLET_INDEX',
  CURRENT_WALLET_CODE: 'CURRENT_WALLET_CODE',
  ADJUSTMENT_NOTIFICATION_DATE: 'ADJUSTMENT_NOTIFICATION_DATE',
};
