# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and canary builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denoland/setup-deno

name: Test dependencies update

on:
  pull_request:
    branches: [v4]

jobs:
  build_package:
    runs-on: macOS-latest # runs a publish on macOS

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Run build
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn install
      - run: yarn package-all
